### ISSUE TITLE
怎么在用户连接的时候获取用户信息

### ISSUE THREAD

**Issue by ciweigg2** [YeautyYE/netty-websocket-spring-boot-starter#1]
怎么在onopen中获取自定义参数

**Comment by ciweigg2** [comment]
我希望是获取用户id 我要知道是谁登录了 具体应该怎么接收这个参数呢，方便的话留个联系方式呀

**Comment by YeautyYE** [comment]
1.可以设置唯一标示在cookie中，onOpen有HttpHeaders参数可以获取请求头的所有内容
2.可以连接后，客户端把唯一标示传输给服务端，服务端的onMessage中接收
你可以通过YeautyYE@gmail.com邮箱联系我，或者可以把微信号发给我

**Comment by ciweigg2** [comment]
501942857
