### ISSUE TITLE
不同用户建立连接的话，怎么确认用户身份？

### ISSUE THREAD

**Issue by wenzhouzhao** [YeautyYE/netty-websocket-spring-boot-starter#12]

**Comment by YeautyYE** [comment]
你说的Session应该是javax.servlet.http.HttpSession 。
通常这种情况是spring-websocket配合spring-mvc一起使用的时候可以这么操作。
因为是共用同一个Servlet容器（如tomcat），在Controller里面先对Session进行setAttribute()。接着可以在HandshakeInterceptor中通过servletRequest.getServletRequest().getSession() 获取到Session，从而拿到相印的attribute。
但这个框架使用的是Netty，而不是Servlet容器，所以无法用这种方法获取到Spring自带Session中的Attribute

如果需要获取用户身份，目前可以有2种方法
1. 将用户的唯一标识设置在cookie中，通过@open注解方法上的参数HttpHeaders 来获取cookie。
2. 连接成功后，客户端主动把用户信息或唯一标识推给服务端即可

**Comment by fanpeng1100** [comment]
header中没有找到cookie
![qq 20181108091043](https://user-images.githubusercontent.com/21329175/48171296-4d55ae00-e336-11e8-9f71-365837ece669.png)
![qq 20181108091058](https://user-images.githubusercontent.com/21329175/48171297-4d55ae00-e336-11e8-80c5-b0176017bbc4.png)

**Comment by YeautyYE** [comment]
> ![qq 20181108092646](https://user-images.githubusercontent.com/21329175/48171797-7119f380-e338-11e8-9ccf-a7d435dcc157.png)
> 还有个问题，服务器主动推消息，这种方式对吗？

服务器主动推的例子如下:
session.sendText("Hello Netty!");
`@OnMessage` 注解的方法是以回调的方式接收客户端的消息

只需要把`快速启动`里面的复制到项目中,不需要配合springmvc.正常跑起来就可以了

**Comment by fanpeng1100** [comment]
@onpen要是能扩展几个参数就好了，我尝试在ws连接时以?token=xxx的方式，这样连接不上。cookie确实没有在ws连接时传送，不知道原因是什么

**Comment by YeautyYE** [comment]
> @onpen要是能扩展几个参数就好了，我尝试在ws连接时以?token=xxx的方式，这样连接不上。cookie确实没有在ws连接时传送，不知道原因是什么

谢谢你的建议,之后会扩展请求参数.关于cookie,可以了解下cookie中域的概念

**Comment by YeautyYE** [comment]
目前版本已支持获取请求参数，只需在@OnOpen注解的方法加上ParameterMap 参数即可（参考`快速启动`）

**Comment by guyuexue** [comment]
配合一个http请求,先通过http请求验证用户,再下发一个token,建立socket链接时将token传过去.

**Comment by mzjdy** [comment]
> 大佬，ParameterMap这个如何请求，是用ws:/ip:port/token=xxx来获取吗

**Comment by YeautyYE** [comment]
> > 大佬，ParameterMap这个如何请求才能拿到，是用ws://ip:port/token=xxx来获取吗，试了半天发现并不能用

和普通的get请求一样即可
如:ws://ip:port?token=xxx

**Comment by YeautyYE** [comment]
> > > > 大佬，ParameterMap这个如何请求才能拿到，是用ws://ip:port/token=xxx来获取吗，试了半天发现并不能用
> > 
> > 
> > 和普通的get请求一样即可
> > 如:ws://ip:port?token=xxx
> 
> 但是这样，我的确没映射过去，不知道是不是姿势不对

你可以把代码发出来,我们看看

**Comment by mzjdy** [comment]
> > > > 大佬，ParameterMap这个如何请求才能拿到，是用ws://ip:port/token=xxx来获取吗，试了半天发现并不能用
> > 
> > 
> > 和普通的get请求一样即可
> > 如:ws://ip:port?token=xxx
> 
> 但是这样，我的确没映射过去，不知道是不是姿势不对
我就是用的你的案例
import io.netty.handler.codec.http.HttpHeaders;
import io.netty.handler.timeout.IdleStateEvent;
import org.springframework.stereotype.Component;
import org.yeauty.annotation.*;
import org.yeauty.pojo.ParameterMap;
import org.yeauty.pojo.Session;

import java.io.IOException;

@ServerEndpoint
@Component
public class WebSocketServer{

    @OnOpen
    public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
        System.out.println("new connection");

        String paramValue = parameterMap.getParameter("paramKey");
        System.out.println(paramValue);
    }

    @OnClose
    public void onClose(Session session) throws IOException {
        System.out.println("one connection closed");
    }

    @OnError
    public void onError(Session session, Throwable throwable) {
        throwable.printStackTrace();
    }

    @OnMessage
    public void onMessage(Session session, String message) {
        System.out.println(message);
        session.sendText("Hello Netty!");
    }

    @OnBinary
    public void onBinary(Session session, byte[] bytes) {
        for (byte b : bytes) {
            System.out.println(b);
        }
        session.sendBinary(bytes);
    }

    @OnEvent
    public void onEvent(Session session, Object evt) {
        if (evt instanceof IdleStateEvent) {
            IdleStateEvent idleStateEvent = (IdleStateEvent) evt;
            switch (idleStateEvent.state()) {
                case READER_IDLE:
                    System.out.println("read idle");
                    break;
                case WRITER_IDLE:
                    System.out.println("write idle");
                    break;
                case ALL_IDLE:
                    System.out.println("all idle");
                    break;
                default:
                    break;
            }
        }
    }

}

**Comment by mzjdy** [comment]
> > > > > 大佬，ParameterMap这个如何请求才能拿到，是用ws://ip:port/token=xxx来获取吗，试了半天发现并不能用
> > > 
> > > 
> > > 和普通的get请求一样即可
> > > 如:ws://ip:port?token=xxx
> > 
> > 
> > 但是这样，我的确没映射过去，不知道是不是姿势不对
> > 我就是用的你的案例
> > import io.netty.handler.codec.http.HttpHeaders;
> > import io.netty.handler.timeout.IdleStateEvent;
> > import org.springframework.stereotype.Component;
> > import org.yeauty.annotation.*;
> > import org.yeauty.pojo.ParameterMap;
> > import org.yeauty.pojo.Session;
> 
> import java.io.IOException;
> 
> @ServerEndpoint
> @component
> public class WebSocketServer{
> 
> ```
> @OnOpen
> public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
>     System.out.println("new connection");
> 
>     String paramValue = parameterMap.getParameter("paramKey");
>     System.out.println(paramValue);
> }
> 
> @OnClose
> public void onClose(Session session) throws IOException {
>     System.out.println("one connection closed");
> }
> 
> @OnError
> public void onError(Session session, Throwable throwable) {
>     throwable.printStackTrace();
> }
> 
> @OnMessage
> public void onMessage(Session session, String message) {
>     System.out.println(message);
>     session.sendText("Hello Netty!");
> }
> 
> @OnBinary
> public void onBinary(Session session, byte[] bytes) {
>     for (byte b : bytes) {
>         System.out.println(b);
>     }
>     session.sendBinary(bytes);
> }
> 
> @OnEvent
> public void onEvent(Session session, Object evt) {
>     if (evt instanceof IdleStateEvent) {
>         IdleStateEvent idleStateEvent = (IdleStateEvent) evt;
>         switch (idleStateEvent.state()) {
>             case READER_IDLE:
>                 System.out.println("read idle");
>                 break;
>             case WRITER_IDLE:
>                 System.out.println("write idle");
>                 break;
>             case ALL_IDLE:
>                 System.out.println("all idle");
>                 break;
>             default:
>                 break;
>         }
>     }
> }
> ```
> }


import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.yeauty.standard.ServerEndpointExporter;


@Configuration
public class WebSocketConfig {

    @Bean
    public ServerEndpointExporter serverEndpointExporter() {
        return new ServerEndpointExporter();
    }

}

**Comment by YeautyYE** [comment]
如果你的url是  : ws://ip:port?token=xxx

String paramValue = parameterMap.getParameter("paramKey");
改成
String tokenValue = parameterMap.getParameter("token");
即可

**Comment by mzjdy** [comment]
> > > > > > 大佬，ParameterMap这个如何请求才能拿到，是用ws://ip:port/token=xxx来获取吗，试了半天发现并不能用
> > > > 
> > > > 
> > > > 和普通的get请求一样即可
> > > > 如:ws://ip:port?token=xxx
> > > 
> > > 
> > > 但是这样，我的确没映射过去，不知道是不是姿势不对
> > > 我就是用的你的案例
> > > import io.netty.handler.codec.http.HttpHeaders;
> > > import io.netty.handler.timeout.IdleStateEvent;
> > > import org.springframework.stereotype.Component;
> > > import org.yeauty.annotation.*;
> > > import org.yeauty.pojo.ParameterMap;
> > > import org.yeauty.pojo.Session;
> > 
> > 
> > import java.io.IOException;
> > @ServerEndpoint
> > @component
> > public class WebSocketServer{
> > ```
> > @OnOpen
> > public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
> >     System.out.println("new connection");
> > 
> >     String paramValue = parameterMap.getParameter("paramKey");
> >     System.out.println(paramValue);
> > }
> > 
> > @OnClose
> > public void onClose(Session session) throws IOException {
> >     System.out.println("one connection closed");
> > }
> > 
> > @OnError
> > public void onError(Session session, Throwable throwable) {
> >     throwable.printStackTrace();
> > }
> > 
> > @OnMessage
> > public void onMessage(Session session, String message) {
> >     System.out.println(message);
> >     session.sendText("Hello Netty!");
> > }
> > 
> > @OnBinary
> > public void onBinary(Session session, byte[] bytes) {
> >     for (byte b : bytes) {
> >         System.out.println(b);
> >     }
> >     session.sendBinary(bytes);
> > }
> > 
> > @OnEvent
> > public void onEvent(Session session, Object evt) {
> >     if (evt instanceof IdleStateEvent) {
> >         IdleStateEvent idleStateEvent = (IdleStateEvent) evt;
> >         switch (idleStateEvent.state()) {
> >             case READER_IDLE:
> >                 System.out.println("read idle");
> >                 break;
> >             case WRITER_IDLE:
> >                 System.out.println("write idle");
> >                 break;
> >             case ALL_IDLE:
> >                 System.out.println("all idle");
> >                 break;
> >             default:
> >                 break;
> >         }
> >     }
> > }
> > ```
> > }
> 
> import org.springframework.context.annotation.Bean;
> import org.springframework.context.annotation.Configuration;
> import org.yeauty.standard.ServerEndpointExporter;
> 
> @configuration
> public class WebSocketConfig {
> 
> ```
> @Bean
> public ServerEndpointExporter serverEndpointExporter() {
>     return new ServerEndpointExporter();
> }
> ```
> }

大佬看下，是不是姿势不对

**Comment by mzjdy** [comment]
> > 大佬看下，是不是姿势不对
> 
> 如果你的url是 : ws://ip:port?token=xxx
> 
> String paramValue = parameterMap.getParameter("paramKey");
> 改成
> String tokenValue = parameterMap.getParameter("token");
> 即可

![image](https://user-images.githubusercontent.com/13652993/50401210-b5b5fd00-07c7-11e9-940c-12c09dc0de66.png)
大佬，真的不是这个问题

**Comment by mzjdy** [comment]
> > > > 大佬看下，是不是姿势不对
> > > 
> > > 
> > > 如果你的url是 : ws://ip:port?token=xxx
> > > String paramValue = parameterMap.getParameter("paramKey");
> > > 改成
> > > String tokenValue = parameterMap.getParameter("token");
> > > 即可
> > 
> > 
> > 大佬，真的不是这个问题
> > ws://localhost:80?token=xxx
> > @onopen
> > public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
> > System.out.println("new connection");
> > ```
> >     String paramValue = parameterMap.getParameter("token");
> >     System.out.println(paramValue);
> > }
> > ```
> 
> 你的client放出来看看

我用的websocket客户端gui版
![image](https://user-images.githubusercontent.com/13652993/50402026-19432900-07ce-11e9-981a-6f4221291f90.png)

**Comment by mzjdy** [comment]
> > > > > 大佬看下，是不是姿势不对
> > > > 
> > > > 
> > > > 如果你的url是 : ws://ip:port?token=xxx
> > > > String paramValue = parameterMap.getParameter("paramKey");
> > > > 改成
> > > > String tokenValue = parameterMap.getParameter("token");
> > > > 即可
> > > 
> > > 
> > > 大佬，真的不是这个问题
> > > ws://localhost:80?token=xxx
> > > @onopen
> > > public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
> > > System.out.println("new connection");
> > > ```
> > >     String paramValue = parameterMap.getParameter("token");
> > >     System.out.println(paramValue);
> > > }
> > > ```
> > 
> > 
> > 你的client放出来看看
> 
> 我用的websocket客户端gui版
> ![image](https://user-images.githubusercontent.com/13652993/50402026-19432900-07ce-11e9-981a-6f4221291f90.png)

是客户端的问题，我换了一个可以了，醉了，感谢大佬解答

**Comment by YeautyYE** [comment]
> > > > > 大佬看下，是不是姿势不对
> > > > 
> > > > 
> > > > 如果你的url是 : ws://ip:port?token=xxx
> > > > String paramValue = parameterMap.getParameter("paramKey");
> > > > 改成
> > > > String tokenValue = parameterMap.getParameter("token");
> > > > 即可
> > > 
> > > 
> > > 大佬，真的不是这个问题
> > > ws://localhost:80?token=xxx
> > > @onopen
> > > public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
> > > System.out.println("new connection");
> > > ```
> > >     String paramValue = parameterMap.getParameter("token");
> > >     System.out.println(paramValue);
> > > }
> > > ```
> > 
> > 
> > 你的client放出来看看
> 
> 我用的websocket客户端gui版
> ![image](https://user-images.githubusercontent.com/13652993/50402026-19432900-07ce-11e9-981a-6f4221291f90.png)

我不确定你这个客户端与浏览器区别,

> > > > > > 大佬看下，是不是姿势不对
> > > > > 
> > > > > 
> > > > > 如果你的url是 : ws://ip:port?token=xxx
> > > > > String paramValue = parameterMap.getParameter("paramKey");
> > > > > 改成
> > > > > String tokenValue = parameterMap.getParameter("token");
> > > > > 即可
> > > > 
> > > > 
> > > > 大佬，真的不是这个问题
> > > > ws://localhost:80?token=xxx
> > > > @onopen
> > > > public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
> > > > System.out.println("new connection");
> > > > ```
> > > >     String paramValue = parameterMap.getParameter("token");
> > > >     System.out.println(paramValue);
> > > > }
> > > > ```
> > > 
> > > 
> > > 你的client放出来看看
> > 
> > 
> > 我用的websocket客户端gui版
> > ![image](https://user-images.githubusercontent.com/13652993/50402026-19432900-07ce-11e9-981a-6f4221291f90.png)
> 
> 是客户端的问题，我换了一个可以了，醉了，感谢大佬解答

https://www.jianshu.com/p/c74ec278a99f
这里有测试用例,直接复制黏贴打开就可以用了

**Comment by mzjdy** [comment]
> > > > > > 大佬看下，是不是姿势不对
> > > > > 
> > > > > 
> > > > > 如果你的url是 : ws://ip:port?token=xxx
> > > > > String paramValue = parameterMap.getParameter("paramKey");
> > > > > 改成
> > > > > String tokenValue = parameterMap.getParameter("token");
> > > > > 即可
> > > > 
> > > > 
> > > > 大佬，真的不是这个问题
> > > > ws://localhost:80?token=xxx
> > > > @onopen
> > > > public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
> > > > System.out.println("new connection");
> > > > ```
> > > >     String paramValue = parameterMap.getParameter("token");
> > > >     System.out.println(paramValue);
> > > > }
> > > > ```
> > > 
> > > 
> > > 你的client放出来看看
> > 
> > 
> > 我用的websocket客户端gui版
> > ![image](https://user-images.githubusercontent.com/13652993/50402026-19432900-07ce-11e9-981a-6f4221291f90.png)
> 
> 我不确定你这个客户端与浏览器区别,
> 
> > > > > > > 大佬看下，是不是姿势不对
> > > > > > 
> > > > > > 
> > > > > > 如果你的url是 : ws://ip:port?token=xxx
> > > > > > String paramValue = parameterMap.getParameter("paramKey");
> > > > > > 改成
> > > > > > String tokenValue = parameterMap.getParameter("token");
> > > > > > 即可
> > > > > 
> > > > > 
> > > > > 大佬，真的不是这个问题
> > > > > ws://localhost:80?token=xxx
> > > > > @onopen
> > > > > public void onOpen(Session session, HttpHeaders headers, ParameterMap parameterMap) throws IOException {
> > > > > System.out.println("new connection");
> > > > > ```
> > > > >     String paramValue = parameterMap.getParameter("token");
> > > > >     System.out.println(paramValue);
> > > > > }
> > > > > ```
> > > > 
> > > > 
> > > > 你的client放出来看看
> > > 
> > > 
> > > 我用的websocket客户端gui版
> > > ![image](https://user-images.githubusercontent.com/13652993/50402026-19432900-07ce-11e9-981a-6f4221291f90.png)
> > 
> > 
> > 是客户端的问题，我换了一个可以了，醉了，感谢大佬解答
> 
> https://www.jianshu.com/p/c74ec278a99f
> 这里有测试用例,直接复制黏贴打开就可以用了

大佬，已经确定是客户端的问题了，多谢回答
