### ISSUE TITLE
android和web前端相互通信的demo

### ISSUE THREAD

**Issue by LuXiaoQiang** [YeautyYE/netty-websocket-spring-boot-starter#14]
有android+web前端+后台的demo吗？

**Comment by YeautyYE** [comment]
前端+后端的demo在这里：https://blog.csdn.net/Yeauty/article/details/82787823
安卓的没有

**Comment by LuXiaoQiang** [comment]
> 前端+后端的demo在这里：https://blog.csdn.net/Yeauty/article/details/82787823
> 安卓的没有

大佬，安卓的有没有打算整一个？

**Comment by YeautyYE** [comment]
安卓的WebSocket Client 百度上应该有很多demo

**Comment by LuXiaoQiang** [comment]
大佬，请教一下我原先本地测试的配置文件path:/  host:0.0.0.0,这个本地连接是正常的，现在发布到外网，是域名地址的，这时候还是这个配置，会连接失败，请问这个连接外网域名需要怎么配置？
