### ISSUE TITLE
wildcard support

### ISSUE THREAD

**Issue by remoteme** [YeautyYE/netty-websocket-spring-boot-starter#15]
Hello, 
is it possible to make path wildard I tried:
path =/**
I tried it like this but instead of wildcard it only allows me to create connection uwint path:
new WebSocket("ws://127.0.0.1:8085/**"); //javascript
new WebSocket("ws://127.0.0.1:8085/something/something /asd");//javascript this douesnt work

but it deonst work as expected

Thanks

**Comment by YeautyYE** [comment]
Sorry It dosen't support wildcard.

**Comment by remoteme** [comment]
thanks :(
