### ISSUE TITLE
怎么获取客户端ip呢&&放在docker里面的问题

### ISSUE THREAD

**Issue by poorcharlie** [YeautyYE/netty-websocket-spring-boot-starter#160]
通过nginx 或者gateway 转发又或者放在docker里面的话，怎么获取客户端真实的ip 地址呢？
并且在docker里面连接进来立马就自动session close了

**Comment by YeautyYE** [comment]
> 通过nginx 或者gateway 转发又或者放在docker里面的话，怎么获取客户端真实的ip 地址呢？
> 并且在docker里面连接进来立马就自动session close了

在nginx后面获取客户端ip，只需要nginx把ip放到header就可以
在docker里面close没遇到过，是客户端直接连不上还是什么情况

**Comment by poorcharlie** [comment]
已经解决了，是运维把项目部署到docker集群里了，所以ip 获取不到。后来拿出来了做单点就正常了

**Comment by YeJiahao-China** [comment]
> 已经解决了，是运维把项目部署到docker集群里了，所以ip 获取不到。后来拿出来了做单点就正常了

我也遇到这个问题了  不过我的微服务模块都是单独run的  不知道为什么会获取不到  nginx关闭之后仍然获取不到
