### ISSUE TITLE
大佬什么时候发布新版本呢？

### ISSUE THREAD

**Issue by 350078238** [YeautyYE/netty-websocket-spring-boot-starter#167]
大佬什么时候发布新版本呢？
增加ws 和 wss的协议，等了一年多了呢
快透漏下你的计划吧

**Comment by YeautyYE** [comment]
不好意思啊，最近加班比较多，预计过年会补一下wss

**Comment by 350078238** [comment]
大佬 ，支持WSS 协议的，已经开发好了是吗？还是在开发中呢？

**Comment by YeautyYE** [comment]
已经开发完了，在测试中，我推了代码

**Comment by YeautyYE** [comment]
已经推到maven中央仓库了，预计6小时后可以拉到。

**Comment by 350078238** [comment]
大佬太给力了， 我现在用0.95   WSS 是用 NGINX 代理实现的
直接用 使用SSL 支持WSS ，要比用NGINX  稳定很多吧？

**Comment by YeautyYE** [comment]
> 大佬太给力了， 我现在用0.95 WSS 是用 NGINX 代理实现的
> 直接用 使用SSL 支持WSS ，要比用NGINX 稳定很多吧？

其实一样稳定，只是可以省一个Nginx的资源
