### ISSUE TITLE
关于断线重连有什么好的解决方案呢? 谢谢

### ISSUE THREAD

**Issue by alfredchennn** [YeautyYE/netty-websocket-spring-boot-starter#174]
默认是30000ms超时, 超时了或者断网了 如何重连呢

**Comment by YeautyYE** [comment]
> 默认是30000ms超时, 超时了或者断网了 如何重连呢

建议客户端定时发送心跳。
重连只需要客户端在关闭事件中重新调用连接方法即可

**Comment by alfredchennn** [comment]
现在是这样的, 客户端没有发心跳, 但是断开了也有做重连, 但有时候长久未操作, 客户端也重连了, 再次发送消息, 服务端也有推送给客户端日志, 但是客户端就是无法收到推送, 请问这个问题是属于什么问题呢?

**Comment by alfredchennn** [comment]
中间网络情况 也比较复杂, 有连接vpn的情况

**Comment by YeautyYE** [comment]
> 中间网络情况 也比较复杂, 有连接vpn的情况

有一种比较常见的情况是中间有Nginx，Nginx会有自己的超时时间。
长时间没有数据通过，就会被关闭连接。
建议客户端定时发送心跳

**Comment by YeautyYE** [comment]
> 现在是这样的, 客户端没有发心跳, 但是断开了也有做重连, 但有时候长久未操作, 客户端也重连了, 再次发送消息, 服务端也有推送给客户端日志, 但是客户端就是无法收到推送, 请问这个问题是属于什么问题呢?

有可能服务端推的是一个已经断开的连接。
由于中间过了很多层，只是客户端与它连接的中间件断了，但服务端和中间件没断。

**Comment by alfredchennn** [comment]
> > 现在是这样的, 客户端没有发心跳, 但是断开了也有做重连, 但有时候长久未操作, 客户端也重连了, 再次发送消息, 服务端也有推送给客户端日志, 但是客户端就是无法收到推送, 请问这个问题是属于什么问题呢?
> 
> 有可能服务端推的是一个已经断开的连接。
> 由于中间过了很多层，只是客户端与它连接的中间件断了，但服务端和中间件没断。

解决问题了, 谢谢你
