### ISSUE TITLE
zuul 网关

### ISSUE THREAD

**Issue by wuwu955** [YeautyYE/netty-websocket-spring-boot-starter#175]
这个项目 支持 zuul 网关吗

**Comment by YeautyYE** [comment]
支持指的是哪部分
如果是协议部分，zuul本身支持转发，所以没问题
如果是服务发现部分，需要自己实现

**Comment by wuwu955** [comment]
> 支持指的是哪部分
> 如果是协议部分，zuul本身支持转发，所以没问题
> 如果是服务发现部分，需要自己实现

例如  前端new WebSocket("ws://网关ip:prot/其他服务/ServerEndpoint 路径/参数") 这样子能建立连接吗

**Comment by YeautyYE** [comment]
> > 支持指的是哪部分
> > 如果是协议部分，zuul本身支持转发，所以没问题
> > 如果是服务发现部分，需要自己实现
> 
> 例如 前端new WebSocket("ws://网关ip:prot/其他服务/ServerEndpoint 路径/参数") 这样子能建立连接吗

不能，WebSocket不会注册到注册中心。
你可以按照zuul的标准注册上去就可以了

**Comment by wuwu955** [comment]
> > > 支持指的是哪部分
> > > 如果是协议部分，zuul本身支持转发，所以没问题
> > > 如果是服务发现部分，需要自己实现
> > 
> > 
> > 例如 前端new WebSocket("ws://网关ip:prot/其他服务/ServerEndpoint 路径/参数") 这样子能建立连接吗
> 
> 不能，WebSocket不会注册到注册中心。
> 你可以按照zuul的标准注册上去就可以了

好的 我先关掉这个问题了
