### ISSUE TITLE
把starter全部代码直接拷贝到我自己工程中启动

### ISSUE THREAD

**Issue by xiangyaoping** [YeautyYE/netty-websocket-spring-boot-starter#182]
由于项目需求需要修改starter源码，就把starter全部代码直接拷贝到我自己工程中启动，启动后日志输出“Netty WebSocket started on port: 8866 with context path(s): '/newfuture' ”，表示websocket启动成功了，但是用客户端去连接却一直卡住，进入不了 @BeforeHandshake
    public void handshake(）方法，仅仅是tcp端口监听成功。求解

**Comment by YeautyYE** [comment]
如果不是直接拷贝的能正常运行吗

**Comment by xiangyaoping** [comment]
> 如果不是直接拷贝的能正常运行吗

直接引用starter是可以正常运行的

**Comment by xiangyaoping** [comment]
直接引用starter包是可以正常运行的哦







在 2021-04-24 22:26:40，"Yeauty" ***@***.***> 写道：

如果不是直接拷贝的能正常运行吗

**Comment by xiangyaoping** [comment]
启动是提示成功的，我是把代码放在我自己项目中的depend包下。客户端连接一直卡在 “等待服务器Websocket握手包...”，也就是走不到不握手代码




在 2021-04-24 22:26:40，"Yeauty" ***@***.***> 写道：

如果不是直接拷贝的能正常运行吗

**Comment by YeautyYE** [comment]
可能包名不对或者其他问题，可以把代码给我看看

**Comment by xiangyaoping** [comment]
问题已解决，netty版本的问题，谢谢大佬啊 







在 2021-04-25 10:39:43，"Yeauty" ***@***.***> 写道：

可能包名不对或者其他问题，可以把代码给我看看

**Comment by YeautyYE** [comment]
好的
