### ISSUE TITLE
请问在@BeforeHandshake 做验证 ,怎么通知前端 验证失败?

### ISSUE THREAD

**Issue by neffoor** [YeautyYE/netty-websocket-spring-boot-starter#186]
你好,在@BeforeHandshake 做验证 ,怎么通知前端 验证失败?

**Comment by YeautyYE** [comment]
只能直接close，因为握手没完成

**Comment by neffoor** [comment]
hi,再问一个问题,我用阿里云服务器测试 4核心16g内存, 并开了10台客户端机器用netty websocket client连.
