### ISSUE TITLE
本地可以，放上生产服务器用不了

### ISSUE THREAD

**Issue by dearkz** [YeautyYE/netty-websocket-spring-boot-starter#191]
生产环境使用docker，端口已经映射好了。一开始以为是nginx没配置好，我把服务器防火墙打开了直接连ip:port，都没办法连接上是什么问题呢。我看应用开启的时候是有打印
o.y.standard.ServerEndpointExporter - Netty WebSocket started on port: 65522 with context path(s): '/ws' .
这句话的

**Comment by dearkz** [comment]
已经肯定是docker部署的问题了。
Dockerfile:
`FROM openjdk:8-jdk-alpine
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar /app.jar" ]`

**Comment by YeautyYE** [comment]
好的
