### ISSUE TITLE
CONNECT_TIMEOUT_MILLIS 的超时的问题

### ISSUE THREAD

**Issue by wanghaoyuissun** [YeautyYE/netty-websocket-spring-boot-starter#192]
没用过netty ,但是看文档 CONNECT_TIMEOUT_MILLIS,表示客户端调用服务端接口的超时时间；想问下 如果想已经建立@OnOpen 后session，比如超过30分钟的session，这个需要自己去session .remove() 吗 ？或者是有配置 吗 ？

**Comment by YeautyYE** [comment]
如果连接断开，会自动调用OnClose，不需要手动remove

**Comment by wanghaoyuissun** [comment]
我是想，超过30分钟的session，服务端强制去close 掉，想问怎么操作 ，是循环remove？ 还是有超时的配置？

**Comment by YeautyYE** [comment]
> 我是想，超过30分钟的session，服务端强制去close 掉，想问怎么操作 ，是循环remove？ 还是有超时的配置？

配置了超时时间，框架会自己去close

**Comment by wanghaoyuissun** [comment]
因为我测试了下，没有自动去close，所有有点奇怪  ,是这么配置的吧 ？
@ServerEndpoint(port = "8050",optionConnectTimeoutMillis = "1000")

**Comment by zhangjiayi1** [comment]
> 我是想，超过30分钟的session，服务端强制去close 掉，想问怎么操作 ，是循环remove？ 还是有超时的配置？

netty有这么一个配置
                          // 30s如果没有收到数据 发生一个事件
                            ch.pipeline().addLast(new IdleStateHandler(30, 0, 0));
                            ch.pipeline().addLast(new ChannelDuplexHandler() {
                                // 出发特殊事件
                                @Override
                                public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
                                    IdleStateEvent event = (IdleStateEvent) evt;
                                    if (event.state() == IdleState.READER_IDLE) {
                                        MyChannelHandlerPool.channelGroup.close(new MyMacher(ctx.channel().id().asLongText()));
                                        MyChannelHandlerPool.channelMaps.remove(ctx.channel().id().asLongText());
                                        SocketRecordService socketRecordService =
                                                SpringUtil.getBean(SocketRecordService.class);
                                        socketRecordService.close(ctx.channel().id().asLongText());
                                    }

                                    super.userEventTriggered(ctx, evt);
                                }
                            });
                            
      还有nginx有最大连接时长的配置  都会使连接断开

**Comment by wanghaoyuissun** [comment]
@zhangjiayi1 谢谢，我看过netty 有这段代码，而且看了 有封装好的配置 刚好：
@ServerEndpoint(port = "${netty-websocket.port}", writerIdleTimeSeconds = "${netty-websocket.writerIdleTimeSeconds}")
 @OnEvent
    public void onEvent(Session session, Object evt) {........
