### ISSUE TITLE
能有什么方法能看到websocket服务器的握手包是否已经发送吗？

### ISSUE THREAD

**Issue by Todddday** [YeautyYE/netty-websocket-spring-boot-starter#193]
![image](https://user-images.githubusercontent.com/31390657/123354914-2c99ff80-d597-11eb-8918-21f81f95816c.png)
![image](https://user-images.githubusercontent.com/31390657/123355024-5fdc8e80-d597-11eb-8aac-660251aff15c.png)
可以看到服务器已经触发了onopen，可是一直没有给客户端返回握手信息。我的服务器是阿里云的，有可能是阿里云的问题吗？

**Comment by YeautyYE** [comment]
onOpen里面写了什么

**Comment by Todddday** [comment]
onopen解析了url，保存用户信息和session

**Comment by YeautyYE** [comment]
从日志来看，是被close了。onOpen有close的逻辑吗？

**Comment by Todddday** [comment]
没有，close是心跳关闭的。1分钟没有心跳就关闭

**Comment by YeautyYE** [comment]
自己写一个html试试

```html
<!DOCTYPE html>
<html lang="en">
<body>
<div id="msg"></div>
<input type="text" id="text">
<input type="submit" value="send" onclick="send()">
</body>
<script>
    var msg = document.getElementById("msg");
    var wsServer = 'ws://127.0.0.1:80';
    var websocket = new WebSocket(wsServer);
    //监听连接打开
    websocket.onopen = function (evt) {
        msg.innerHTML = "The connection is open";
    };
 
    //监听服务器数据推送
    websocket.onmessage = function (evt) {
        msg.innerHTML += "<br>" + evt.data;
    };
 
    //监听连接关闭
    websocket.onclose = function (evt) {
        alert("连接关闭");
    };
 
    function send() {
        var text = document.getElementById("text").value
        websocket.send(text);
    }
</script>
</html>
```

**Comment by Todddday** [comment]
![image](https://user-images.githubusercontent.com/31390657/123363246-a4225b80-d5a4-11eb-980d-d3dae90cefcc.png)
还是不行

**Comment by Todddday** [comment]
![image](https://user-images.githubusercontent.com/31390657/123363749-bd77d780-d5a5-11eb-976b-97ac9ca97072.png)
![image](https://user-images.githubusercontent.com/31390657/123363762-c5d01280-d5a5-11eb-9fcc-e81b08105887.png)
本地是完全没有问题的

**Comment by YeautyYE** [comment]
用的同一个客户端吗

**Comment by Todddday** [comment]
是的

**Comment by YeautyYE** [comment]
> 是的

服务器是否有安全配置（如白名单、iptable、firewalld）

服务器上抓包看看请求是否到了（可以tcpdump）
