### ISSUE TITLE
kill进程不成功

### ISSUE THREAD

**Issue by zhangys529** [YeautyYE/netty-websocket-spring-boot-starter#196]
大佬你好，有时候kill停止进程的时候会出现停止不掉的情况，日志中会报Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x1e9c72ff]警告，紧接着会报Failed to submit a listener notification task. Event loop shut down?错误，是不是我代码方面哪里没有写对呢，我目前是实现了ServerEndpointExporter的bean注解，ServerEndpoint注解类中实现了OnOpen、OnClose、OnMessage，并且使用了Autowired注入一些service，能否帮忙分析一下，谢谢哈！

**Comment by YeautyYE** [comment]
正常情况，kill的时候会优雅关闭连接。
可以换成`kill -9`强制关闭
