### ISSUE TITLE
异常情况疑问

### ISSUE THREAD

**Issue by guotg5** [YeautyYE/netty-websocket-spring-boot-starter#198]
onError方法什么场景会进入呢？
如果想处理发送消息失败的场景，直接在ChannelFuture上注册监听是否可行，还是直接用onError方法即可。
消息发送失败可以获取到对应的消息吗？

**Comment by YeautyYE** [comment]
直接用onError就可以了。
发送消息失败不能获取对应的消息，因为如果发失败，不是消息的问题，而是网络的问题了
