### ISSUE TITLE
内存占用越来越多，且不会释放

### ISSUE THREAD

**Issue by HaoLee404** [YeautyYE/netty-websocket-spring-boot-starter#202]
操作系统：CentOS
配置：4核8G
场景：建立500个websocket连接，每秒从rabbitmq接收100个消息，每条消息都会遍历这500个连接向客户端推送。
问题：直接内存占用缓慢增加，且一直不会释放。

**Comment by HaoLee404** [comment]
还有一个是堆内存占用高的问题，本来想另提一个，干脆也在这里问了。同样也是这次压测过程中发现的，就是一开始堆内存占用不高，但是随着压测的进行，堆内存也快满了。用Eclipse Memory Analyzer看了下堆内存使用情况：
![企业微信截图_16279027875506](https://user-images.githubusercontent.com/88318896/127853306-85d7785f-ec4a-4f1d-94c1-aed93df54551.png)
![图片](https://user-images.githubusercontent.com/88318896/127853390-8f2a6a09-174b-4c76-9e62-fc01b695b8af.png)
发现是Channel占用了比较多的内存，但我才建500个连接啊。而且整个过程都是500个连接，为什么一开始占用不高，后面内存占用越来越多？
![图片](https://user-images.githubusercontent.com/88318896/127853625-508e5fa5-6ded-4dfd-95dc-6b65b7cbb15e.png)
再看Channel的引用链，这个层次结构是不是有什么问题？我还没点完，感觉像个循环链表。
另外，由于堆内存的老年代被占满了，所以垃圾回收线程一直在工作，导致CPU也满载了。
![企业微信截图_16278915632480](https://user-images.githubusercontent.com/88318896/127854249-6ffd2839-885c-4731-90be-753b0f77a064.png)

**Comment by YeautyYE** [comment]
可以先看看rabbitmq的客户端是否也用到了netty
然后再发下代码

**Comment by HaoLee404** [comment]
> 
> 
> 可以先看看rabbitmq的客户端是否也用到了netty
> 然后再发下代码

我刚看了下，我的工程里确实有多个版本的netty依赖，我先统一下版本，然后再看看这个问题

**Comment by YeautyYE** [comment]
> 我刚看了下，我的工程里确实有多个版本的netty依赖，我先统一下版本，然后再看看这个问题

要识别下，上面的Channel是来自本框架的，还是来自其他框架的

**Comment by HaoLee404** [comment]
> 
> 
> > 我刚看了下，我的工程里确实有多个版本的netty依赖，我先统一下版本，然后再看看这个问题
> 
> 要识别下，上面的Channel是来自本框架的，还是来自其他框架的

我另起了一个项目，只依赖了此库，压测发现直接内存增长到一定程度就不再增长了，java堆也没有出现溢出的情况，同时客户端也能正常接收服务端推送的消息。那我之前遇到的问题可能跟版本冲突有关，具体原因我还需要继续验证。

**Comment by YeautyYE** [comment]
> 我另起了一个项目，只依赖了此库，压测发现直接内存增长到一定程度就不再增长了，java堆也没有出现溢出的情况，同时客户端也能正常接收服务端推送的消息。那我之前遇到的问题可能跟版本冲突有关，具体原因我还需要继续验证。

嗯，如果压测是固定的请求量，那内存最终是稳定的

**Comment by HaoLee404** [comment]
这个内存溢出问题经过反复测试和验证，发现跟本库无关，是客户端的锅。测试人员写的python websocket客户端在接收大量数据时，性能非常差，服务端数据发不出去全堆积在缓冲区了，所以会导致内存溢出，而我用java websocket客户端测试则没有这个问题。所以为了服务端的稳定性，开发者可以在发送数据时加上如下代码：
```
long bytesBeforeWritable = session.channel().bytesBeforeWritable();
if (bytesBeforeWritable <= channelBufferSizeThreshold) {
	if (session.isActive()) {
		return session.sendText(message);
	}
} else {
	switch (bufferThresholdExceededPolicy) {
		case BufferThresholdExceededPolicy.CLOSE_SESSION_VALUE:
			session.close();
			break;
		case BufferThresholdExceededPolicy.DISCARD_VALUE:
			break;
		case BufferThresholdExceededPolicy.PERSISTENCE_VALUE:
			fileOperator.saveSendFailMsg(message);
			break;
	}
}
```
如果策略是将发送失败的消息写到硬盘，注意要立马刷盘，不能放在缓冲区，否则基本是解决了个寂寞。
最后，说下吞吐量，给大家提供一个参考。单机发消息能跑满500MBit/s的带宽，1G内存就能hold住，CPU的四个核心还没跑满，单核心最高飙到70%. 而且我的代码并不是一个啥逻辑都没有的简单demo, 里面有一些协议解析和封装的逻辑。总的来说，性能是合格的。

**Comment by YeautyYE** [comment]
赞！
