### ISSUE TITLE
你好，请问支持微服务注册发现吗？

### ISSUE THREAD

**Issue by wowlike** [YeautyYE/netty-websocket-spring-boot-starter#219]
我用的nacos，好像注册不上去

**Comment by likedeke** [comment]
找到解决方案了

![image](https://user-images.githubusercontent.com/65269574/149272751-cb8c2a63-6b48-4c72-af09-470fc65d40e7.png)

**Comment by aronftd** [comment]
能发注册nacos的完整类吗，多谢！@fzdwx

**Comment by fzdwx** [comment]
> 能发注册nacos的完整类吗，多谢！@fzdwx

就是手动调用这个`start()`方法就可以了，它这个就是监听那个`event`的回调，而`netty-websocket-spring-boot-starte`这个包没有发送这个`event`

**Comment by fzdwx** [comment]
> 能发注册nacos的完整类吗，多谢！@fzdwx

你要这个类是吧，时间太久了，我忘记了，不过应该不难找。

可以看看它的`starter` or `autoConfiguration`?
