### ISSUE TITLE
本地运行正常，docker部署websocket连接失败！

### ISSUE THREAD

**Issue by idler41** [YeautyYE/netty-websocket-spring-boot-starter#233]
版本： 0.12.0
问题描述：本地启动websocket服务，与前端项目联调功能正常，docker部署后websocket连接失败
场景描述：websocket宿主机与容器内都是绑定9999端口，容器内telnet 端口 9999能测通，应用也有日志打印
![企业微信截图_1656574403412](https://user-images.githubusercontent.com/9761979/176619636-6d73681f-56b8-47f6-aa48-0901aa007306.png)

但在宿主机上或局域网其他主机上telnet端口9999就会立即出现Connection closed by foreign host，后台也没有上面截图的日志

![企业微信截图_16565747455973](https://user-images.githubusercontent.com/9761979/176620740-38180e8e-dbc2-4349-bf64-351c9ee1d519.png)

docker容器截图：

![企业微信截图_16565745931112](https://user-images.githubusercontent.com/9761979/176620277-690e0016-23d5-4f88-b125-ab6427305f29.png)

这是啥原因导致的？还有现在是否有交流群？

补充：ws.host这个配置的作用是什么？我另外一个websocket项目也是用的netty，好像只需要配置端口就可以。我给ws.host配置了一个自定义的域名websocket.xxx.com，是否是这个参数的影响？对netty了解比较浅，希望可以解答下

**Comment by idler41** [comment]
补充：我ws.host改为0.0.0.0问题解决，但还是希望知道ws.host的作用是什么，谢谢

**Comment by YeautyYE** [comment]
这是一种安全策略，决定你需要监听的IP是什么。
基本上所有基础设施的搭建都是这样的
