### ISSUE TITLE
Content-length of blob is 0?

### ISSUE THREAD

**Issue by YamagataKe** [YeautyYE/netty-websocket-spring-boot-starter#27]
The image sended is not displayed in the browser using the following code:

  var ws = new WebSocket('ws://127.0.0.1:8080')
  ws.binaryType = 'blob'

**Comment by YamagataKe** [comment]
I think it is caused by the following：

public class Session {
....

    public ChannelFuture sendBinary(ByteBuffer byteBuffer) {
        ByteBuf buffer = channel.alloc().buffer(byteBuffer.remaining());
        return channel.writeAndFlush(new BinaryWebSocketFrame(buffer));

->  should be :
        return channel.writeAndFlush(new BinaryWebSocketFrame(buffer.writeBytes(
        		byteBuffer.array(), byteBuffer.position(), byteBuffer.remaining() ) ) );
        		
    }

**Comment by YeautyYE** [comment]
Oh! Thanks! 
This is a bug.
It will be fixed in next version.

**Comment by YeautyYE** [comment]
fixed
