### ISSUE TITLE
多端点描述疑惑点

### ISSUE THREAD

**Issue by Y-lenny** [YeautyYE/netty-websocket-spring-boot-starter#28]
你好，请问下“当地址相同,路径(path)不同时,使用同一个ServerBootstrap实例”，这句话怎么理解？
我的理解是：多@ServerEndpoint(path = UrlMappingConsts.V1_BOOTSTRAP)路径配置（地址+端口不变）那么他们的session是同一个？ 可以这么理解吗

或者说我需要实现这种功能请问下你的框架是否支持？ 
Tips 我之所以想通过这种方式区分主要目的是能否让业务能单一化在某个类中。

**Comment by YeautyYE** [comment]
在Netty中，每一个ServerBootstrap需要初始化N条线程（一般情况下倾向于相对较少的线程）。
但如果需求是不同的业务在不同的类中，其实并不需要关注这个概念，直接用就可以了（最开始的设计也是为了实现这个需求）

**Comment by Y-lenny** [comment]
我在使用过程当中确实是可以按照业务区分类的形式；我所担心的点是假如每个类的ServerEndpoint都对应一个新会话也就是代表客户端需要根据业务频繁切换ws会话；那么这种从性能上的考虑设计上是否问题（因为ws是长连接其实是可以做到多业务并存一个ServerEndpoint中的）；假如说地址+端口能确保会话是一个那么会不会好点呢

**Comment by YeautyYE** [comment]
在浏览器中,每一个WebSocket对象成功连接后就是一个会话, 当你关闭之后再去连接,就是一个新的会话.
请问你说的切换会话指的是频繁的关闭一个连接去创建另一个连接吗? 这样做的话,确实不合理.可以有更好的方案.

**Comment by Y-lenny** [comment]
举个游戏的栗子：创建房间，开始游戏我目前设计在两个 ServerEndpoint中；那么假如一个用户需要做这么两个事情是在一个会话当中吗

**Comment by YeautyYE** [comment]
如果你对两个 ServerEndpoint 都进行了连接,那就是创建了2个会话.
即使你是对同一个 ServerEndpoint 创建2条连接,也是2个会话.
这里通常的会话是与连接对应,与常用说的http中会话的定义不一样.
所以尽量不要把不同的ServerEndpoint 当作http中的不同api进行请求,这样不太合理

**Comment by Y-lenny** [comment]
理解了，“尽量不要把不同的ServerEndpoint 当作http中的不同api进行请求,这样不太合理” 对于这个你有什么好的设计思路吗？以什么样的维度归因到一个ServerEndpoint 呢？

**Comment by YeautyYE** [comment]
主要是2点.
1.根据功能业务进行划分ServerEndpoint
2.用户可以一直保持同一条连接(一直连接到同一个ServerEndpoint),而不是进行连接切换
举个栗子:
在消息推送的场景可以分成两个 ServerEndpoint .
普通的用户连接第一个ServerEndpoint,服务器会推送一般的消息.
VIP用户连接到第二个ServerEndpoint,服务器会推送收费的消息.

**Comment by Y-lenny** [comment]
感谢，我突然发现我的API设计角度还是沿用了http的思维考虑了...
