### ISSUE TITLE
0.7.4是否已经支持wss

### ISSUE THREAD

**Issue by MrCxin** [YeautyYE/netty-websocket-spring-boot-starter#32]
如题

**Comment by YeautyYE** [comment]
还不支持wss

**Comment by MrCxin** [comment]
get tks

**Comment by MrCxin** [comment]
我这边down下你的code引入我自己的项目 在此基础上按照常规的在initChannel的时候加入SslHandler可以自己实现wss么
(因为我试了下发现并没有成功)

**Comment by MrCxin** [comment]
@YeautyYE

**Comment by YeautyYE** [comment]
正常来说是可以的
或者你可以把代码发出来看看

**Comment by MrCxin** [comment]
ok  之前我是用的ip+端口 网上看到一些说wss要用域名  我先试下

**Comment by YeautyYE** [comment]
OK

**Comment by MrCxin** [comment]
@YeautyYE 
有其他优先级的事情处理, 暂时先用nginx转发来实现wss
感谢老哥

**Comment by YeautyYE** [comment]
> @YeautyYE
> 有其他优先级的事情处理, 暂时先用nginx转发来实现wss
> 感谢老哥

不客气
