### ISSUE TITLE
prefix 配置无效

### ISSUE THREAD

**Issue by zhouguoxun** [YeautyYE/netty-websocket-spring-boot-starter#34]
你好，prefix配置无效。版本用的最新0.7.5

**Comment by zhouguoxun** [comment]
顺便还可以给一下参数调优项吗？谢谢 😀

**Comment by YeautyYE** [comment]
请问你是怎么配置的,能发下相关的application.propertise和@ServerEndpoint上的属性吗?

**Comment by zhouguoxun** [comment]
好的。。
@ServerEndpoint(prefix="netty-websocket")
@Component
这是注解项。

application.properties
netty-websocket.host=0.0.0.0
netty-websocket.path=/im
netty-websocket.port=8085

我用客户端访问以上配置路径404

**Comment by YeautyYE** [comment]
你是用浏览器直接发起get请求吗？
还是常规websocket请求

**Comment by zhouguoxun** [comment]
常规websocket请求，如果我用spring注解配置参数是ok的。

**Comment by YeautyYE** [comment]
> 常规websocket请求，如果我用spring注解配置参数是ok的。

测试正常,可否看你的完整代码? 
我邮箱 YeautyYE@gmail.com

**Comment by zhouguoxun** [comment]
sorry。我刚刚检查我的代码，是因为同级目录下还有个ServerEndpoint 用的spring注解，所以导致我另外一个ServerEndpoint 无法使用prefix注解。谢谢解答。
