### ISSUE TITLE
wss现在支持吗？

### ISSUE THREAD

**Issue by loostars** [YeautyYE/netty-websocket-spring-boot-starter#35]

**Comment by loostars** [comment]
请问 wss现在支持了吗？

**Comment by YeautyYE** [comment]
不支持

**Comment by loostars** [comment]
了解。期待和等待中 ~-~

**Comment by shuaiyinoo** [comment]
可以用Nginx做个WSS的代理 到java的ws上面

**Comment by cpstory** [comment]
意思是说，需要用java来实现一个rtsp的客户端进行转流吗？通过wss的方式将接收到的rtsp响应给页面？


------------------ 原始邮件 ------------------
发件人: "帅印"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 下午3:41
收件人: "YeautyYE/netty-websocket-spring-boot-starter"<netty-websocket-spring-boot-starter@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [YeautyYE/netty-websocket-spring-boot-starter] wss现在支持吗？ (#35)




可以用Nginx做个WSS的代理 到java的ws上面

**Comment by shuaiyinoo** [comment]
不是
单纯的用nginx做个代理
