### ISSUE TITLE
我这边想实现群聊和一对一聊天

### ISSUE THREAD

**Issue by yjy1992** [YeautyYE/netty-websocket-spring-boot-starter#40]
我看了问题《一对一发消息应该怎么做》这边我发现貌似没办法通过 "/netty/{userId}" 这种方式把userId获取到对应的变量中去，不支持socket的PathParam注解啊。用“/netty”可以访问，用 "/netty/{userId}"直接报404.

**Comment by yjy1992** [comment]
我没办法知道用户的userId没办法维护列表啊。

**Comment by yjy1992** [comment]
@YeautyYE

**Comment by yjy1992** [comment]
我看到你说的新版本支持 parameterMap 了。我先试试

**Comment by YeautyYE** [comment]
> 我看到你说的新版本支持 parameterMap 了。我先试试

是的

**Comment by yjy1992** [comment]
获取到了userId。谢咯。
