### ISSUE TITLE
你好,我在服务器部署了服务以后,然后用客户端访问的时候报错了,麻烦你帮忙提下意见

### ISSUE THREAD

**Issue by small-ora** [YeautyYE/netty-websocket-spring-boot-starter#41]
客户端的操作是先发送一段文本(大概100个字符),然后再分段发送一些二进制的数据,在发送文本的时候服务端报错,我在网上查询了一下,以为是'最大允许帧载荷长度'太小了,但是调大5倍还是不行,希望您能帮忙提一下意见,谢谢.
![1](https://user-images.githubusercontent.com/33921583/56953417-2357a880-6b6f-11e9-8f59-e23a8a6d8b3e.jpg)
期待您的答复.

**Comment by small-ora** [comment]
找到问题,是握手的时候服务端返回的字段有点不符合标准,所以客户端识别错误就报错了.
![2](https://user-images.githubusercontent.com/33921583/57186992-f6164c00-6f1a-11e9-8d1f-4e5d4a79b690.png)
标准的返回应该是:Sec-WebSocket-Accept

**Comment by YeautyYE** [comment]
> 找到问题,是握手的时候服务端返回的字段有点不符合标准,所以客户端识别错误就报错了.
> ![2](https://user-images.githubusercontent.com/33921583/57186992-f6164c00-6f1a-11e9-8d1f-4e5d4a79b690.png)
> 标准的返回应该是:Sec-WebSocket-Accept

根据W3C,Headers是大小写不敏感的.
所以,并不是大写就是标准,小写也要兼容.并且HTTP2是需要小写的.

参考:https://www.ietf.org/rfc/rfc2616.txt   `4.2 Message Headers`

**Comment by small-ora** [comment]
明白了,对不起,是我资料查的不全,造成了误解,感谢您的指教.

**Comment by small-ora** [comment]
> > 找到问题，是握手的时候服务端返回的字段有点不符合标准，所以客户端识别错误就报错了。
> > 标准的返回应该是：二段的WebSocket-接受
> > ![2](https://user-images.githubusercontent.com/33921583/57186992-f6164c00-6f1a-11e9-8d1f-4e5d4a79b690.png)
> 
> 根据W3C，头是大小写不敏感的。
> 所以，并不是大写就是标准，小写也要兼容。并且HTTP2是需要小写的。
> 
> 参考：[https](https://www.ietf.org/rfc/rfc2616.txt)：[//www.ietf.org/rfc/rfc2616.txt](https://www.ietf.org/rfc/rfc2616.txt) `4.2 Message Headers`

明白了,对不起,是我资料查的不全,造成了误解,感谢您的指教.

**Comment by YeautyYE** [comment]
> 
> 明白了,对不起,是我资料查的不全,造成了误解,感谢您的指教.

客气
