### ISSUE TITLE
咨询一下，要做两个人PK的答题游戏能实现吗

### ISSUE THREAD

**Issue by tjthink** [YeautyYE/netty-websocket-spring-boot-starter#44]
您好，我现在要做两个人PK的答题游戏，大致流程如下
1、登录系统，标识为所有登录的人是在线的
2、某用户发起PK游戏，建立房间，给在线用户发起消息，最先进入的人与发起者进行游戏
3、系统推送题目给在同一房间的两个人，进行PK，相互推送答题结果

**Comment by YeautyYE** [comment]
能实现

**Comment by tjthink** [comment]
> 能实现

我参照了： 
您好，如果服务端是集群模式，如何拿到session，怎么向客户端发送消息 #2 这个已经关闭的问题；
如何通过 serverId向客户端发送消息呢

**Comment by YeautyYE** [comment]
> > 能实现
> 
> 我参照了：
> 您好，如果服务端是集群模式，如何拿到session，怎么向客户端发送消息 #2 这个已经关闭的问题；
> 如何通过 serverId向客户端发送消息呢

serverid只是服务端的标志,你可以以服务端的ip:port为一个serverid

**Comment by tjthink** [comment]
> > > 能实现
> > 
> > 
> > 我参照了：
> > 您好，如果服务端是集群模式，如何拿到session，怎么向客户端发送消息 #2 这个已经关闭的问题；
> > 如何通过 serverId向客户端发送消息呢
> 
> serverid只是服务端的标志,你可以以服务端的ip:port为一个serverid

嗯，我是准备这做，如何发送消息的时候，我不知道如何通过ip:port去新建或是怎么去找到原来的服务器关发送消息

**Comment by YeautyYE** [comment]
> 嗯，我是准备这做，如何发送消息的时候，我不知道如何通过ip:port去新建或是怎么去找到原来的服务器关发送消息

假设你的websocket服务端是一个集群.
那么每个websocket服务就会对应着一个ip:port.
你可以把这个ip:port存到一个地方,如redis.
当你需要发送消息的时候,你就可以从redis取出来,知道自己有哪几个服务.
然后可以通过MQ或者请求的方式告诉对应的服务,你需要推送消息出去.

更进一步的说,如果你需要知道哪个人是连着哪个服务. 你redis也可以存{serverid}:{userid}
那么你就会知道每个服务下有哪些用户正在连接

**Comment by tjthink** [comment]
> > 嗯，我是准备这做，如何发送消息的时候，我不知道如何通过ip:port去新建或是怎么去找到原来的服务器关发送消息
> 
> 假设你的websocket服务端是一个集群.
> 那么每个websocket服务就会对应着一个ip:port.
> 你可以把这个ip:port存到一个地方,如redis.
> 当你需要发送消息的时候,你就可以从redis取出来,知道自己有哪几个服务.
> 然后可以通过MQ或者请求的方式告诉对应的服务,你需要推送消息出去.
> 
> 更进一步的说,如果你需要知道哪个人是连着哪个服务. 你redis也可以存{serverid}:{userid}
> 那么你就会知道每个服务下有哪些用户正在连接

第一次接触这种推送所以有些地方不是很明白，如果不用MQ,怎么样请求去告诉服务应该推消息了呢
![image](https://user-images.githubusercontent.com/5283107/58932757-96b88f80-8797-11e9-9de4-01327e6eab92.png)

**Comment by YeautyYE** [comment]
> 第一次接触这种推送所以有些地方不是很明白，如果不用MQ,怎么样请求去告诉服务应该推消息了呢
> ![image](https://user-images.githubusercontent.com/5283107/58932757-96b88f80-8797-11e9-9de4-01327e6eab92.png)

其实就是跨进程的通信.
跨进程通信方式很多.
每个服务提供一个http接口,需要发的时候请求一下也行

**Comment by tjthink** [comment]
> > 第一次接触这种推送所以有些地方不是很明白，如果不用MQ,怎么样请求去告诉服务应该推消息了呢
> > ![image](https://user-images.githubusercontent.com/5283107/58932757-96b88f80-8797-11e9-9de4-01327e6eab92.png)
> 
> 其实就是跨进程的通信.
> 跨进程通信方式很多.
> 每个服务提供一个http接口,需要发的时候请求一下也行

还是没明白怎样能让对应的服务器去给相应的人员发消息

**Comment by YeautyYE** [comment]
> 
> 还是没明白怎样能让对应的服务器去给相应的人员发消息

你们的连接数如果不是10万以上,并且每秒消息发送数量不到10万,那就不需要集群,单机就可以了.
单机的话,直接一个map就可以通过key找到你需要的session

**Comment by yueyemisi** [comment]
YeautyYE 的意思应该是 拿到ip+port后直接去请求的对应的http接口，再去本地内存里获取对应的用户发消息。
集群下用MQ的广播消费或者redis 的广播通知

**Comment by tjthink** [comment]
-
