### ISSUE TITLE
client在连接server后报Connection reset by peer 

### ISSUE THREAD

**Issue by maning711** [YeautyYE/netty-websocket-spring-boot-starter#46]
client在连接server的事件后，很快会触发一次异常，具体信息为【Connection reset by peer 】，server 端的连接处理并没有什么报错，难道是client的异常或者处理顺序导致的？求助～

**Comment by YeautyYE** [comment]
> client在连接server的事件后，很快会触发一次异常，具体信息为【Connection reset by peer 】，server 端的连接处理并没有什么报错，难道是client的异常或者处理顺序导致的？求助～

那证明server还没创建连接就被reset了.尝试下换成chrome浏览器的websocket client来做实验.看是否正常

**Comment by maning711** [comment]
我用jmeter模拟websocket发送请求，没有遇到这个报错

**Comment by YeautyYE** [comment]
> 我用jmeter模拟websocket发送请求，没有遇到这个报错

是否用jmeter模拟的时候,并没有正常关闭连接(发送websocket的关闭操作),而是直接强制断开.
简单的说,这个错误是在连接断开后的读和写操作引起的。

**Comment by maning711** [comment]
嗯，其实我怀疑是client那边的开发在操作时可能有两个请求同时打到ws，正好前一个是断开，后一个是读写；jmeter的测试模板是顺序的，所以没问题。。

**Comment by YeautyYE** [comment]
> 嗯，其实我怀疑是client那边的开发在操作时可能有两个请求同时打到ws，正好前一个是断开，后一个是读写；jmeter的测试模板是顺序的，所以没问题。。

好的

**Comment by maning711** [comment]
经过我们排查，发现使用的CMQ的CLB前置策略里有一个75s空闲会自动切断连接，而当时client的心跳逻辑是120秒一次。。。导致没有来得及保活就被切断了，我们自己的逻辑的锅，到此，该问题关闭。感谢 YE

**Comment by maning711** [comment]
经过我们排查，发现使用的CMQ的CLB前置策略里有一个75s空闲会自动切断连接，而当时client的心跳逻辑是120秒一次。。。导致没有来得及保活就被切断了，我们自己的逻辑的锅，到此，该问题关闭。感谢 YE
