### ISSUE TITLE
请问一下，关于服务端发送消息，多个相同客户端页面只能某一个接受到的情况

### ISSUE THREAD

**Issue by wangzengjing** [YeautyYE/netty-websocket-spring-boot-starter#47]
就是我客户端同样的页面同时打开三个，都是传同样的paramKey放到一个map里面，然后我在服务端从map取出这个paramKey的session发送消息，但是客户端只有某一个可以得到消息，有什么办法可以让所有页面都得到消息吗？

**Comment by YeautyYE** [comment]
> 就是我客户端同样的页面同时打开三个，都是传同样的paramKey放到一个map里面，然后我在服务端从map取出这个paramKey的session发送消息，但是客户端只有某一个可以得到消息，有什么办法可以让所有页面都得到消息吗？

- 不同的页面意味着是不同的连接,也就是不同的session
- 如果传的paramKey是一样的,并且是通过这个作为唯一标识来区分,那map中应该只会有一个
- 如果需要多个相同的paramKey都收到消息,map可以可以改成Map<String,List<Session>>.map的key为paramKey

**Comment by wangzengjing** [comment]
嗯嗯，好的，谢谢大佬指点
