### ISSUE TITLE
怎么获取客户端的ip地址

### ISSUE THREAD

**Issue by jianxw** [YeautyYE/netty-websocket-spring-boot-starter#54]
目前是通过
String ipStr = ((InetSocketAddress) session.channel().remoteAddress()).getAddress().getHostAddress(); 
来获取ip地址的，但是如果通过nginx做了负载均衡的话，是获取到的nginx的ip地址 而不是客户单端ip地址

**Comment by YeautyYE** [comment]
> 目前是通过
> String ipStr = ((InetSocketAddress) session.channel().remoteAddress()).getAddress().getHostAddress();
> 来获取ip地址的，但是如果通过nginx做了负载均衡的话，是获取到的nginx的ip地址 而不是客户单端ip地址

OnOpen事件中有headers参数.可以从中获取到头信息.
Nginx可以把真实IP放到这里 (PHP就是这么做的)

**Comment by jianxw** [comment]
可以了，谢谢
