### ISSUE TITLE
在群发消息的时候性能很低

### ISSUE THREAD

**Issue by machinezhou** [YeautyYE/netty-websocket-spring-boot-starter#56]
楼主你好，在做测试的时候发现群发消息的地方性能很低，错误率很高：

`public static void broadcast(String message) {
        for (Session session : OBSERVABLE.getSessions()) {
            if (session.isOpen()) {
                sendMessage(session, message);
            }
        }
    }`

上面代码就是通过遍历session来做分发消息，测试的是用的200个线程来模拟客户端，请问是我哪里操作不对还是说你也遇到过？

**Comment by machinezhou** [comment]
首先得感谢楼主分享

**Comment by YeautyYE** [comment]
请问性能差是怎么体现出来的？是在服务端测出来的还是客户端。

1. 如果客户端和服务端不在同一个服务器上，可以考虑下带宽问题
2. 如果在同一台服务器上，可以先查看资源是否不足，或者是客户端性能跟不上。

**Comment by YeautyYE** [comment]
当发送量非常大 (如:100000/s)，可以使用堆外内存(零拷贝提升性能)来群发进行优化

demo:
```java
        // sessions 为 List<Session>
        String str = "Hello Netty!";
        byte[] bytes = str.getBytes();
        ByteBuf buf = PooledByteBufAllocator.DEFAULT.buffer(bytes.length).writeBytes(bytes);
        try {
            for (Session session : sessions) {
                if (session.isWritable()) {
                    session.sendText(buf.retainedDuplicate());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            ReferenceCountUtil.release(buf);
        } 
```

**Comment by machinezhou** [comment]
谢谢楼主回复，我是用的jmeter测试工具在本地进行测试的，我再看看代码有没有问题再试你的方法。
