### ISSUE TITLE
多个相同程序使用的时候出现java.net.BindException: Address already in use: bind异常

### ISSUE THREAD

**Issue by wangzengjing** [YeautyYE/netty-websocket-spring-boot-starter#57]
你好，我开了两个相同的程序，然后把其中一个程序80端口改成88，两个一起启动的时候就会报占用地址的异常，但是单开其中任何一个是没有问题的，请问这是什么情况？

**Comment by YeautyYE** [comment]
请排查两个程序是否各自只占用80或88端口

**Comment by wangzengjing** [comment]
刚刚去查看了一下，好像两个都是用了80的端口，在配置文件中更改端口不生效

**Comment by YeautyYE** [comment]
> 刚刚去查看了一下，好像两个都是用了80的端口，在配置文件中更改端口不生效

配置文件和@ServerEndpoint是什么内容，可以发出来看看

**Comment by wangzengjing** [comment]
抱歉，问题查出，是我自己的问题，我是用application.yml去配置，与application.properties有点不同，格式写错，换回到application.properties问题解决！感谢作者耐心教导

**Comment by YeautyYE** [comment]
> 抱歉，问题查出，是我自己的问题，我是用application.yml去配置，与application.properties有点不同，格式写错，换回到application.properties问题解决！感谢作者耐心教导

解决就好
