### ISSUE TITLE
springboot起10个项目做负载 怎么样websocket连接能共享啊

### ISSUE THREAD

**Issue by chenweibo** [YeautyYE/netty-websocket-spring-boot-starter#65]
多服务 websocket 能共享然后推送信息吗 怎么做的 有没有例子

**Comment by YeautyYE** [comment]
如果需要做成分布式应用,下面的思路也许是一种简单的解决方案
需要:
redis(memcached) 用来存client唯一标示(如:userId) 和server唯一标示(如: ip)
kafka(rocketmq、rabbitmq) 用于异步通知相应的server发送消息
流程:
1.当client连接时,在redis中存入userId:serverIp,并在当前应用的一个map中添加userId和对应的session
2.当需要对某client发送消息时,先去redis中查出对应的serverIp,通过kafka推送一条消息(topic:serverIp key:userId value:content)
3.当对应的server收到消息时,找到 第 1 步中的map ,把相应的session获取到,调用sendText()方法发送消息
4.当client关闭连接时,把redis中相应的记录删除
tips1:以上是主要的流程,没有提到如server挂掉时,如何把redis中的记录删除,其实有很多解决方案,如加上过期时间 .
tips2:建议通过装饰者模式,将session和上面的部分流程集成起来,以后的调用者会更加的舒服

**Comment by traceless0929** [comment]
也可以使用 redis 的订阅发布功能代替kafka,每个节点都订阅规则如:wsEndpoint_{serverIp}
1.client连接时，redis中map记录所在server 保存映射关系，在本地也保存好userId和session的映射关系
2.client发消息时，到map中找到目标client所在server，往wsEndpoint_{目标serverIp}发消息如:userid content
3.每个server在收到自己订阅的wsEndpoint_{本serverIp}消息后，解析出userId和content，利用userId找到本机中的session，发送给这个session

核心思路和楼上其实一致，只是使用redis自带订阅发布功能 少使用一个kafka

**Comment by zhangyaoo** [comment]
> 也可以使用 redis 的订阅发布功能代替kafka,每个节点都订阅规则如:wsEndpoint_{serverIp} 1.client连接时，redis中map记录所在server 保存映射关系，在本地也保存好userId和session的映射关系 2.client发消息时，到map中找到目标client所在server，往wsEndpoint_{目标serverIp}发布息如:userid content 【这里可以先判断是不是本机的session，是的话就直接发，没必要通过redis】 3.每个server在收到自己订阅的wsEndpoint_{本serverIp}消息后，解析出userId和content，利用userId找到本机中的session，发送给这个session
> 
> 核心思路和楼上其实一致，只是使用redis自带订阅发布功能 少使用一个kafka

这样redis太重了，会成为瓶颈，有高可用问题，不建议用redis做消息中转，

**Comment by czqclm** [comment]
各位大佬可以看看我的项目，使用 rabbit + redis 实现的 [netty-websocket-cluster](https://github.com/czqclm/netty-websocket-cluster) 。实际生产中我还用了 gateway 和 nacos，后续我也会更新到这个里面
