### ISSUE TITLE
性能

### ISSUE THREAD

**Issue by cherrishccl** [YeautyYE/netty-websocket-spring-boot-starter#9]
您好，请问做过压测什么的吗，或者有过生产实践没，各方面性能怎么样？

**Comment by YeautyYE** [comment]
该项目在一个股票实时行情推送的生产环境中稳定运行了超过1年。

性能的话，以我们生产中的数据作为回答吧。
单台服务器
CPU:4核 平均使用10%以内  峰值40%左右
内存:8G  堆内存2.5G 堆外内存限制2G 也就是不超过4.5G
连接数: 10000+
每秒推送量: 100000+

连接数没有太大参考意义，毕竟空连接的话百万级别也是没压力的。
推送量的话，正常使用是妥妥的，如果对Netty有一定的了解，可以进行调优。

这个框架其实仅仅是对Netty进行了简单的封装，使其更好的整合进SpringBoot中。在项目运行时，其性能和Netty是一样的

**Comment by cherrishccl** [comment]
好的，多谢，我再测一下

**Comment by I2finance-AxinJL** [comment]
你好，我是直接拿下来的starter，在自己本地电脑测试，只能实现256个连接，如果需要扩大连接数的话，需要配置哪些参数？

**Comment by YeautyYE** [comment]
> 你好，我是直接拿下来的starter，在自己本地电脑测试，只能实现256个连接，如果需要扩大连接数的话，需要配置哪些参数？

查看下系统的最大打开文件描述符数是多少

**Comment by caimingshi** [comment]
你好，请问你们生产的配置是啥样的，我这边4核16g的服务器只能接受4000左右链接 就不行了

**Comment by YeautyYE** [comment]
> 你好，请问你们生产的配置是啥样的，我这边4核16g的服务器只能接受4000左右链接 就不行了

1.检查客户端是否不行了
2.检查最大打开文件描述符是多少
